// function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}

  ## The Task

  The task for the elevent module was to create a Node.js CLI program that allowed the user to generate a README in Markdown using the CLI. The application made use of the Inquirer NPM package, fed a data object of questions and CLI inputs and then wrote to file as a .md file directly into the repo.

  ## Website Screenshot

  ![screenshot-of-image](https://github.com/builtbydans/EDX_Challenge11_README-Generator/blob/main/screenshot.png)

  // BELOW IS THE README GENERATED BY THE PROGRAM

  -------------------------------

  ## Project Description
  ${data.description}

  ## What License Covers This Application?
  ${data.license}

  ## NPM Packages
  inquirer

  ## How Do I Install Dependencies?
  ${data.installation}

  ## How Do I Run Tests?
  ${data.test}

  ## How Can I Run The Program?
  ${data.usage}

  ## How Can I Contribute?
  ${data.contribution}
`;
}

module.exports = generateMarkdown;
